### ISSUE TITLE
It is not possible to launch tests simultaneously

### ISSUE THREAD

**Issue by dmtrrk** [Orcomp/NUnitBenchmarker#1]
All tests execute one by one. Is it possible to execute TestGroup simultaneously?

**Comment by Orcomp** [comment]
It isn't possible as we are relying on Nunit to run the tests.

**Comment by GeertvanHorrik** [comment]
Closing issue, this is something out of our hands. And for best (and most reliable) results, you don't want tests to run at the same time.
